M48
; DRILL file {KiCad (6.0.4)} date Tue Oct 24 13:53:16 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-24T13:53:16+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.360
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X192.02Y-105.01
X204.22Y-105.01
X207.768Y-105.0
X219.968Y-105.0
T2
X170.87Y-75.67
X170.87Y-85.91
T0
M30
